### ISSUE TITLE
Boot options not saved

### ISSUE THREAD

**Issue by ghost** [archfan/coreboot#9]
I want to report that "add boot option" or "change boot order" is not saved on reboot in release v1.1. 
I think no settings are saved.

I flashed the 4MB chip according to https://doc.coreboot.org/mainboard/lenovo/t440p.html.

Internal flashing with flashrom is not supported on T440p or?
Great you did this port!

**Comment by Conor-Burns** [comment]
try building from master - this commit 06e44d0b7c4f774d7464d7568d793d58ec12f372 adds support for saving the bootorder.

**Comment by sudo-gedit** [comment]
@kllp Did you successfully compile and then boot?

**Comment by ghost** [comment]
@sudo-gedit No I flashed the v1.1 release on the release page directly.
Building is hard because it requires the proprietary mrc.bin.
For saving bootorder there is indeed a commit.
Does internal flashing work now if it has been flashed externally?
